# Configurations of Faster R-CNN with SARShip dataset

_base_: ../_base_/sarship.yaml

save_dir: ./test_tipc/output/det/faster_rcnn/

model: !Node
    type: FasterRCNN
    args:
        num_classes: 1