# Basic configurations of RSSR dataset

datasets:
    train: !Node
        type: ResDataset
        args: 
            data_dir: ./test_tipc/data/rssr/
            file_list: ./test_tipc/data/rssr/train.txt
            num_workers: 0
            shuffle: True
            sr_factor: 4
    eval: !Node
        type: ResDataset
        args:
            data_dir: ./test_tipc/data/rssr/
            file_list: ./test_tipc/data/rssr/val.txt
            num_workers: 0
            shuffle: False
            sr_factor: 4
transforms:
    train:
        - !Node
          type: DecodeImg
        - !Node
          type: RandomCrop
          args:
            crop_size: 32
        - !Node
          type: RandomHorizontalFlip
          args:
            prob: 0.5
        - !Node
          type: RandomVerticalFlip
          args:
            prob: 0.5
        - !Node
          type: Normalize
          args:
            mean: [0.0, 0.0, 0.0]
            std: [1.0, 1.0, 1.0]
        - !Node
          type: ArrangeRestorer
          args: ['train']
    eval:
        - !Node
          type: DecodeImg
        - !Node
          type: Resize
          args:
            target_size: 256
        - !Node
          type: Normalize
          args:
            mean: [0.0, 0.0, 0.0]
            std: [1.0, 1.0, 1.0]
        - !Node
          type: ArrangeRestorer
          args: ['eval']
download_on: False
download_url: https://paddlers.bj.bcebos.com/datasets/rssr.zip
download_path: ./test_tipc/data/

num_epochs: 10
train_batch_size: 4
save_interval_epochs: 10
log_interval_steps: 10
save_dir: ./test_tipc/output/res/
learning_rate: 0.0005
early_stop: False
early_stop_patience: 5
use_vdl: False
resume_checkpoint: ''