# Basic configurations of SARShip dataset

datasets:
    train: !Node
        type: VOCDetDataset
        args: 
            data_dir: ./test_tipc/data/sarship/
            file_list: ./test_tipc/data/sarship/train.txt
            label_list: ./test_tipc/data/sarship/labels.txt
            shuffle: True
    eval: !Node
        type: VOCDetDataset
        args:
            data_dir: ./test_tipc/data/sarship/
            file_list: ./test_tipc/data/sarship/eval.txt
            label_list: ./test_tipc/data/sarship/labels.txt
            shuffle: False
transforms:
    train:
        - !Node
          type: DecodeImg
        - !Node
          type: RandomDistort
        - !Node
          type: RandomExpand
        - !Node
          type: RandomCrop
        - !Node
          type: RandomHorizontalFlip
        - !Node
          type: BatchRandomResize
          args:
            target_sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
            interp: RANDOM
        - !Node
          type: Normalize
          args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - !Node
          type: ArrangeDetector
          args: ['train']
    eval:
        - !Node
          type: DecodeImg
        - !Node
          type: Resize
          args:
            target_size: 608
            interp: CUBIC
        - !Node
          type: Normalize
          args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - !Node
          type: ArrangeDetector
          args: ['eval']
download_on: False
download_url: https://paddlers.bj.bcebos.com/datasets/sarship.zip
download_path: ./test_tipc/data/

num_epochs: 10
train_batch_size: 4
save_interval_epochs: 10
log_interval_steps: 4
save_dir: ./test_tipc/output/det/
learning_rate: 0.0001
use_vdl: False
resume_checkpoint: ''
train:
    pretrain_weights: COCO
    warmup_steps: 0
    warmup_start_lr: 0.0