# Basic configurations of FCCDN

_base_: ../_base_/airchange.yaml

save_dir: ./test_tipc/output/cd/fccdn/

learning_rate: 0.07
lr_decay_power: 0.6

log_interval_steps: 100

save_interval_epochs: 3

model: !Node
       type: FCCDN
