# Basic configurations of UCMerced dataset

datasets:
    train: !Node
        type: ClasDataset
        args: 
            data_dir: ./test_tipc/data/ucmerced/
            file_list: ./test_tipc/data/ucmerced/train.txt
            label_list: ./test_tipc/data/ucmerced/labels.txt
            num_workers: 0
            shuffle: True
    eval: !Node
        type: ClasDataset
        args:
            data_dir: ./test_tipc/data/ucmerced/
            file_list: ./test_tipc/data/ucmerced/val.txt
            label_list: ./test_tipc/data/ucmerced/labels.txt
            num_workers: 0
            shuffle: False
transforms:
    train:
        - !Node
          type: DecodeImg
        - !Node
          type: Resize
          args:
            target_size: 256
        - !Node
          type: RandomHorizontalFlip
          args:
            prob: 0.5
        - !Node
          type: RandomVerticalFlip
          args:
            prob: 0.5
        - !Node
          type: Normalize
          args:
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
        - !Node
          type: ArrangeClassifier
          args: ['train']
    eval:
        - !Node
          type: DecodeImg
        - !Node
          type: Resize
          args:
            target_size: 256
        - !Node
          type: Normalize
          args:
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
        - !Node
          type: ArrangeClassifier
          args: ['eval']
download_on: False
download_url: https://paddlers.bj.bcebos.com/datasets/ucmerced.zip
download_path: ./test_tipc/data/

num_epochs: 2
train_batch_size: 16
save_interval_epochs: 10
log_interval_steps: 50
save_dir: ./test_tipc/output/clas/
learning_rate: 0.01
early_stop: False
early_stop_patience: 5
use_vdl: False
resume_checkpoint: ''