# Configurations of PP-YOLO Tiny with SARShip dataset

_base_: ../_base_/sarship.yaml

save_dir: ./test_tipc/output/det/ppyolo_tiny/

model: !Node
    type: PPYOLOTiny
    args:
        num_classes: 1